<?php
	include("session_call.php");
	if($_SESSION['valid_type'] != 'Administrator')
	{
		echo '<script language="javascript">';
			echo 'location.replace("index.php");';
		echo '</script>';
	}
	
	if ((isset($_GET['table'])) && (isset($_GET['id'])) && (isset($_GET['action'])) )
	{
		$table_name = trim($_GET['table']);
		$id = trim($_GET['id']);
		$action = trim($_GET['action']);
	}
	else
	{
		header("location: admin_view.php");
		exit();
	}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US" dir="ltr">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link href="images\icon.ico" rel="shortcut icon" />
		<title>ACDSS | Admin | Edit</title>
		<meta name="viewport" content="initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width" />

		<!--[if lt IE 9]><script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
		<link type="text/css" rel="stylesheet" href="style.css" media="screen" />
		<!--[if lte IE 7]><link type="text/css" rel="stylesheet" href="style.ie7.css" media="screen" /><![endif]-->
		<link type="text/css" rel="stylesheet" href="style.responsive.css" media="all" />

		<script type="text/javascript" src="jquery.js"></script>
		<script type="text/javascript" src="script.js"></script>
		<script type="text/javascript" src="script.responsive.js"></script>
		<meta name="description" content="Description" />
		<meta name="keywords" content="Keywords" />
	</head>
	<body><a name="top"></a>
		<div id="art-main">
			<?php
				include("header.php");
				echo '<p align="right"><font color="white" size="2">Current User: '.strtoupper($_SESSION['valid_username']).'&nbsp;&nbsp;</font></p>';
				include("nav.php");
			?>
			<div class="art-sheet clearfix">
				<div class="art-layout-wrapper clearfix">
					<div class="art-content-layout">
						<div class="art-content-layout-row">
							<div class="art-layout-cell art-content clearfix">
								<article class="art-post art-article">
									<h2 class="art-postheader">Modify Record</h2>
									<div class="art-postcontent art-postcontent-0 clearfix">
									<form action="admin_update.php" method="POST" enctype="multipart/form-data">
										<?php
											include("connection.php");

											$table_name = $_GET['table'];
											$row_id = $_GET['id'];
											$action = $_GET['action'];

											$table_query = mysql_query("SELECT * FROM $table_name WHERE id=$id LIMIT 1") or die("This webpage is not available.<br />".mysql_error());
											if($table_query)
											{
												while($table_row = mysql_fetch_array($table_query))
												{
													if($table_name == "users")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">NAME:</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="user_name" value="'.$table_row['username'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PASSWORD:</td>';
																	echo '<td style="border:0;"><input type="password" style="width:50%"  name="user_pwd" value="'.$table_row['password'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PHOTO:</td>';
																	echo '<td style="border:0;"><input type="file" name="admin_pic" value="" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS:</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="admin_status">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "clients")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;width:10%"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">Barangay</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="client_brgy">';
																			echo '<option selected="selected" value="'.$table_row['brgy'].'">'.$table_row['brgy'].'</option>';
																			echo '<option value="Bagong Nayon">Bagong Nayon</option>';
																			echo '<option value="Beverly Hills">Beverly Hills</option>';
																			echo '<option value="Calawis">Calawis</option>';
																			echo '<option value="Cupang">Cupang</option>';
																			echo '<option value="Dalig">Dalig</option>';
																			echo '<option value="Dela Paz">Dela Paz</option>';
																			echo '<option value="Inarawan">Inarawan</option>';
																			echo '<option value="Mambugan">Mambugan</option>';
																			echo '<option value="Mayamot">Mayamot</option>';
																			echo '<option value="Munting">Munting</option>';
																			echo '<option value="Dilao">Dilao</option>';
																			echo '<option value="San Isidro">San Isidro</option>';
																			echo '<option value="San Jose">San Jose</option>';
																			echo '<option value="San Juan">San Juan</option>';
																			echo '<option value="San Luis">San Luis</option>';
																			echo '<option value="San Roque">San Roque</option>';
																			echo '<option value="Sta Cruz">Sta Cruz</option>';																			
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">FIRST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_fname" value="'.$table_row['fname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MIDDLE NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_mname" value="'.$table_row['mname'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">LAST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_lname" value="'.$table_row['lname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">AGE</td>';
																	echo '<td style="border:0;"><input type="number" style="width:7%"  name="client_age" value="'.$table_row['age'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">RELIGION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_religion" value="'.$table_row['religion'].'" required /></td>';
																echo '</tr>';						
																echo '<tr>';
																	echo '<td style="border:0;">CIVIL STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="client_civilstat">';
																			echo '<option selected="selected" value="'.$table_row['civilstat'].'">'.$table_row['civilstat'].'</option>';
																			echo '<option value="Civil Union">Civil Union</option>';
																			echo '<option value="Divorced">Divorsed</option>';
																			echo '<option value="Married">Married</option>';
																			echo '<option value="Separated">Separated</option>';
																			echo '<option value="Single">Single</option>';
																			echo '<option value="Widow">Widow</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BIRTHDAY</td>';
																	echo '<td style="border:0;"><input type="date" style="width:50%" name="client_bdate" value="'.$table_row['bdate'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BIRTHPLACE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_bplace" value="'.$table_row['bplace'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_address" value="'.$table_row['address'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">EDUCATION</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="client_educ">';
																			echo '<option selected="selected" value="'.$table_row['educ'].'">'.$table_row['educ'].'</option>';
																			echo '<option value="Elementary Level">Elementary Level</option>';
																			echo '<option value="Elementary Graduate">Elementary Graduate</option>';
																			echo '<option value="High School Level">High School Level</option>';
																			echo '<option value="High School Graduate">High School Graduate</option>';
																			echo '<option value="College Graduate">College Graduate</option>';
																			echo '<option value="Post Graduate">Post Graduate</option>';
																			echo '<option value="Vocational">Vocational</option>';
																			echo '<option value="None">None</option>';						
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">JOB</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_job" value="'.$table_row['occupation'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">INFORMANT</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_informant" value="'.$table_row['informant'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">INFORMANT RELATIONSHIP</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_informant_rel" value="'.$table_row['informant_rel'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">ASSISTANCE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="client_assistance">';
																			echo '<option selected="selected" value="'.$table_row['assistance'].'">'.$table_row['assistance'].'</option>';
																			echo '<option value="Counseling">Select Assistance</option>';
																			echo '<option value="Financial">Financial</option>';
																			echo '<option value="Medical">Medical</option>';
																			echo '<option value="Burial">Burial</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">REQUIREMENTS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="client_requirements">';
																			echo '<option elected="selected" value="'.$table_row['requirements'].'">'.$table_row['requirements'].'</option>';
																			echo '<option value="Complete">Complete</option>';
																			echo '<option value="Incomplete">Incomplete</option>';
																			echo '<option value="None">None</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">POST</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="client_post">';
																			echo '<option selected="selected" value="'.$table_row['post'].'">'.$table_row['post'].'</option>';
																			echo '<option value="Approved">Approved</option>';
																			echo '<option value="Pending">Pending</option>';
																			echo '<option value="Re-Apply">Re-Apply</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BUDGET</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_budget" value="'.$table_row['budget'].'" required /></td>';
																echo '</tr>'; 
																	echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_dep_name" value="'.$table_row['dep_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT AGE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_dep_age" value="'.$table_row['dep_age'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT RELATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_dep_rel" value="'.$table_row['dep_rel'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT CIVIL STATUS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_dep_civilstat" value="'.$table_row['dep_civilstat'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT JOB</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_dep_job" value="'.$table_row['dep_job'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT EDUCATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_dep_educ" value="'.$table_row['dep_educ'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">PROBLEM PRESENTED</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_prob_pres" value="'.$table_row['prob_presented'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PRESENT FUCTIONING</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_pres_functioning" value="'.$table_row['present_functioning'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">FAMILY RELATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="client_fam_rel" value="'.$table_row['fam_rel'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SUPPORT SYSTEM</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_support_sys" value="'.$table_row['support_sys'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">ECONOMIC CONDITION</td>';
																	echo '<td style="border:0;"><input type=""" style="width:50%"  name="client_eco_con" value="'.$table_row['eco_condition'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">OTHER ASSISTANCES</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_other_assist" value="'.$table_row['other_assistances'].'" required /></td>';
																echo '</tr>'; 
																echo '<tr>';
																	echo '<td style="border:0;">EVALUATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="client_eval" value="'.$table_row['eval'].'" required /></td>';
																echo '</tr>'; 
																echo '<tr>';
																	echo '<td style="border:0;">STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="client_status">';
																			echo '<option selected="selected" value="'.$table_row['status'].'">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "client_gi")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;width:10%"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">FIRST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_fname" value="'.$table_row['fname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MIDDLE NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_mname" value="'.$table_row['mname'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">LAST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_lname" value="'.$table_row['lname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">GENDER</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_gender">';
																			echo '<option selected="selected" value="'.$table_row['gender'].'">'.$table_row['gender'].'</option>';
																			echo '<option value="Male">Male</option>';
																			echo '<option value="Female">Female</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">AGE</td>';
																	echo '<td style="border:0;"><input type="number" style="width:50%" name="gi_age" value="'.$table_row['age'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SPOUSE NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_spouse_name" value="'.$table_row['spouse_name'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">SPOUSE BIRTHDAY</td>';
																	echo '<td style="border:0;"><input type="date" style="width:50%" name="gi_spouse_bdate" value="'.$table_row['spouse_bdate'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SPOUSE BIRTHPLACE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_spouse_bplace" value="'.$table_row['spouse_bplace'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">CIVIL STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_civilstat">';
																			echo '<option selected="selected" value="'.$table_row['civilstat'].'">'.$table_row['civilstat'].'</option>';
																			echo '<option value="Civil Union">Civil Union</option>';
																			echo '<option value="Divorced">Divorced</option>';
																			echo '<option value="Married">Married</option>';
																			echo '<option value="Separated">Separated</option>';
																			echo '<option value="Single">Single</option>';
																			echo '<option value="Widow">Widow</option>';
																		echo '</select>';
																	echo '</td>';
																echo '<tr>';
																	echo '<td style="border:0;">RELIGION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_religion" value="'.$table_row['religion'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">TELEPHONE NUMBER</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_tel_no" value="'.$table_row['religion'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_address" value="'.$table_row['address'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PROVINCE ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_province_address" value="'.$table_row['religion'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">EDUCATION</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_educ">';
																			echo '<option selected="selected" value="'.$table_row['educ'].'">'.$table_row['educ'].'</option>';
																			echo '<option value="Elementary Level">Elementary Level</option>';
																			echo '<option value="Elementary Graduate">Elementary Graduate</option>';
																			echo '<option value="High School Level>High School Level</option>';
																			echo '<option value="High School Graduate">High School Graduate</option>';
																			echo '<option value="College Graduate">College Graduate</option>';
																			echo '<option value="Post Graduate>Post Graduate</option>';
																			echo '<option value="Vocational">Vocational</option>';
																			echo '<option value="None">None</option>';						
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">PHILHEALTH</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_philhealth" value="'.$table_row['philhealth'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">JOB</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_job" value="'.$table_row['job'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">MONTHLY INCOME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_mo_income" value="'.$table_row['mo_income'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ADMISSION</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_admission">';
																			echo '<option elected="selected" value="'.$table_row['admission'].'">'.$table_row['admission'].'</option>';
																			echo '<option value="Walk-In">Walk-In</option>';
																			echo '<option value="Referral">Referral</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																	echo '<td style="border:0;">REFERRING PARTY</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_referring_party" value="'.$table_row['referring_party'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">REFERRING PARTY ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_referring_party_address" value="'.$table_row['referring_party_address'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">REQUIREMENTS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_requirements">';
																			echo '<option selected="selected" value="'.$table_row['requirements'].'">'.$table_row['requirements'].'</option>';
																			echo '<option value="Complete">Complete</option>';
																			echo '<option value="Incomplete">Incomplete</option>';
																			echo '<option value="None">None</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">POST</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_post">';
																			echo '<option selected="selected" value="'.$table_row['post'].'">'.$table_row['post'].'</option>';
																			echo '<option value="Approved">Approved</option>';
																			echo '<option value="Pending">Pending</option>';
																			echo '<option value="Re-Apply">Re-Apply</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BUDGET</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_budget" value="'.$table_row['budget'].'" required /></td>';
																echo '</tr>';
																echo '</tr>'; 
																	echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_dep_name" value="'.$table_row['dep_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT AGE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_dep_age" value="'.$table_row['dep_age'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT RELATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_dep_rel" value="'.$table_row['dep_rel'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT CIVIL STATUS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_dep_civilstat" value="'.$table_row['dep_civilstat'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT JOB</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_dep_job" value="'.$table_row['dep_job'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">DEPENDENT EDUCATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_dep_educ" value="'.$table_row['dep_educ'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PROBLEM PRESENTED</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_prob_pres" value="'.$table_row['prob_presented'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">WORKERS ASSESSMENT</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_workers_assessment" value="'.$table_row['workers_assessment'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">CLIENT CATEGORY</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_client_cat">';
																			echo '<option selected="selected" value="'.$table_row['client_cat'].'">'.$table_row['client_cat'].'</option>';
																			echo '<option value="Children in Need of Special Protection">Children in Need of Special Protection</option>';
																			echo '<option value="Youth in Need of Special Protection">Youth in Need of Special Protection</option>';
																			echo '<option value="Women in Especially Difficult Circumstances">Women in Especially Difficult Circumstances</option>';
																			echo '<option value="Person with Disability Senior Citizen">Person with Disability Senior Citizen</option>';
																			echo '<option value="Family Head and Other Needy Adult">Family Head and Other Needy Adult</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';			
																echo '<tr>';
																	echo '<td style="border:0;">ASSISTANCE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_assistance">';
																			echo '<option selected="selected" value="'.$table_row['assistance'].'">'.$table_row['assistance'].'</option>';
																			echo '<option value="Counseling">Select Assistance</option>';
																			echo '<option value="Financial">Financial</option>';
																			echo '<option value="Medical">Medical</option>';
																			echo '<option value="Burial">Burial</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';	
																echo '<td style="border:0;">SPECIFICATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="gi_specification" value="'.$table_row['specification'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">VALUE (PESOS)</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_value_pesos" value="'.$table_row['value_pesos'].'" required /></td>';
																echo '</tr>';	
																echo '<tr>';
																	echo '<td style="border:0;">SUBTOTAL</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_subtotal" value="'.$table_row['subtotal'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">AMOUNT IN FIGURES</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_amt_figures" value="'.$table_row['amt_figures'].'" required /></td>';
																echo '</tr>'; 
																echo '<tr>';
																	echo '<td style="border:0;">AMOUNT IN WORDS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="gi_amt_words" value="'.$table_row['amt_words'].'" required /></td>';
																echo '</tr>'; 
																echo '<tr>';
																	echo '<td style="border:0;">MODE OF ASSISTANCE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_assistance_mode">';
																			echo '<option selected="selected" value="'.$table_row['assistance_mode'].'">'.$table_row['assistance_mode'].'</option>';
																			echo '<option value="Cash">Cash</option>';
																			echo '<option value="Check">Check</option>';
																			echo '<option value="Guarantee Letter">Guarantee Letter</option>';
																			
																		echo '</select>';
																	echo '</td>';
																echo '<tr>';
																	echo '<td style="border:0;">SOURCE OF ASSISTANCE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_assistance_source">';
																			echo '<option elected="selected" value="'.$table_row['assistance_source'].'">'.$table_row['assistance_source'].'</option>';
																			echo '<option value="Regular">Regular</option>';
																			echo '<option value="Donation">Donation</option>';
																			echo '<option value="Priority Dev"t Assistance Fund">Priority Dev"t Assistance Fund</option>';
																			echo '<option value="Legislation">Legislation</option>';
																			echo '<option value="Others">Others</option>';																			
																		echo '</select>';
																	echo '</td>';
																echo '<tr>';
																	echo '<td style="border:0;">Assistance Material</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_assistance_material">';
																			echo '<option selected="selected" value="'.$table_row['assistance_material'].'">'.$table_row['assistance_material'].'</option>';
																			echo '<option value="Food Pack">Food Pack</option>';
																			echo '<option value="Used Clothing">Used Clothing</option>';
																			echo '<option value="Hot Meal">Hot Meal</option>';
																			echo '<option value="Assistive Device">Assistive Device</option>';
																			echo '<option value="Others">Others</option>';																			
																		echo '</select>';												
																	echo '</td>';
																echo '<tr>';
																	echo '<td style="border:0;">TOTAL</td>';
																	echo '<td style="border:0;"><input type=""" style="width:50%"  name="gi_total" value="'.$table_row['total'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">Interviewer</td>';
																	echo '<td style="border:0;"><input type=""" style="width:50%"  name="gi_interviewer" value="'.$table_row['interviewer'].'" required /></td>';
																echo '</tr>';
																	echo '<tr>';
																	echo '<td style="border:0;">STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="gi_status">';
																			echo '<option selected="selected" value="'.$table_row['status'].'">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													
													elseif($table_name == "client_pwd")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;width:10%"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';														
																echo '<tr>';
																	echo '<td style="border:0;">FIRST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_fname" value="'.$table_row['fname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MIDDLE NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="pwd_mname" value="'.$table_row['mname'].'" required /></td>';
																echo '</tr>';				
																echo '<tr>';
																	echo '<td style="border:0;">LAST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_lname" value="'.$table_row['lname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">DISABLITY</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_disability" value="'.$table_row['disability'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BIRTHDAY</td>';
																	echo '<td style="border:0;"><input type="date" style="width:50%" name="pwd_bdate" value="'.$table_row['bdate'].'" required /></td>';
																echo '</tr>';
																	echo '<tr>';
																	echo '<td style="border:0;">GENDER</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_gender">';
																			echo '<option selected="selected" value="'.$table_row['gender'].'">'.$table_row['gender'].'</option>';
																			echo '<option value="Male">Male</option>';
																			echo '<option value="Female">Female</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">CIVIL STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_civilstat">';
																			echo '<option selected="selected" value="'.$table_row['civilstat'].'">'.$table_row['civilstat'].'</option>';
																			echo '<option value="Civil Union">Civil Union</option>';
																			echo '<option value="Divorced">Divorced</option>';
																			echo '<option value="Married">Married</option>';
																			echo '<option value="Separated">Separated</option>';
																			echo '<option value="Single">Single</option>';
																			echo '<option value="Widow">Widow</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">EDUCATION</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_educ">';
																			echo '<option selected="selected" value="'.$table_row['educ'].'">'.$table_row['educ'].'</option>';
																			echo '<option value="Elementary Level">Elementary Level</option>';
																			echo '<option value="Elementary Graduate">Elementary Graduate</option>';
																			echo '<option value="High School Level>High School Level</option>';
																			echo '<option value="High School Graduate">High School Graduate</option>';
																			echo '<option value="College Graduate">College Graduate</option>';
																			echo '<option value="Post Graduate>Post Graduate</option>';
																			echo '<option value="Vocational">Vocational</option>';
																			echo '<option value="None">None</option>';						
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';			
																echo '<tr>';
																	echo '<td style="border:0;">ASSISTANCE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_assistance">';
																			echo '<option selected="selected" value="'.$table_row['assistance'].'">'.$table_row['assistance'].'</option>';
																			echo '<option value="Counseling">Select Assistance</option>';
																			echo '<option value="Financial">Financial</option>';
																			echo '<option value="Medical">Medical</option>';
																			echo '<option value="Burial">Burial</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">REQUIREMENTS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_requirements">';
																			echo '<option selected="selected" value="'.$table_row['requirements'].'">'.$table_row['requirements'].'</option>';
																			echo '<option value="Complete">Complete</option>';
																			echo '<option value="Incomplete">Incomplete</option>';
																			echo '<option value="None">None</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">POST</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_post">';
																			echo '<option selected="selected" value="'.$table_row['post'].'">'.$table_row['post'].'</option>';
																			echo '<option value="Approved">Approved</option>';
																			echo '<option value="Pending">Pending</option>';
																			echo '<option value="Re-Apply">Re-Apply</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BUDGET</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="pwd_budget" value="'.$table_row['budget'].'" required /></td>';
																echo '</tr>'; 
																echo '<tr>';
																	echo '<td style="border:0;">ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_address" value="'.$table_row['address'].'" required /></td>';
																echo '</tr>';
															    echo '<tr>';
																	echo '<td style="border:0;">BARANGAY</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_brgy" value="'.$table_row['brgy'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MUNICIPALITY</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_municipality" value="'.$table_row['municipality'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PROVINCE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_province" value="'.$table_row['province'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">REGION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_region" value="'.$table_row['region'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">TELEPHONE NO.</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_telno" value="'.$table_row['telno'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">CELLPHOINE NO.</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_celno" value="'.$table_row['celno'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">EMAIL</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_email" value="'.$table_row['email'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">EMPLOYEE STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_empstat">';
																			echo '<option selected="selected" value="'.$table_row['empstat'].'">'.$table_row['empstat'].'</option>';
																			echo '<option value="Employed">Employed</option>';
																			echo '<option value="Unemployed">Unemployed</option>';
																			echo '<option value="Displaced Worker">Displaced Worker</option>';
																			echo '<option value="Resigned">Resigned</option>';
																			echo '<option value="Retired">Retired</option>';
																			echo '<option value="Returning OFW">Returning OFW</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">EMPLOYER</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_employer">';
																			echo '<option selected="selected" value="'.$table_row['employer'].'">'.$table_row['employer'].'</option>';
																			echo '<option value="Private">Private</option>';
																			echo '<option value="Government">Government</option>';																			
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">EMPLOYMENT</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_employment">';
																			echo '<option selected="selected" value="'.$table_row['employment'].'">'.$table_row['employment'].'</option>';
																			echo '<option value="Contractual">Contractual</option>';
																			echo '<option value="Employement">Employment</option>';
																			echo '<option value="Self_employed">Self Employed</option>';
																			echo '<option value="Seasonal">Seasonal</option>';																				
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SKILL</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_skill">';
																			echo '<option selected="selected" value="'.$table_row['skill'].'">'.$table_row['skill'].'</option>';
																			echo '<option value="Political Official">Political Official</option>';
																			echo '<option value="Manager">Manager</option>';
																			echo '<option value="Professional">Professional</option>';
																			echo '<option value="Technician">Technician</option>';
																			echo '<option value="Clerks">Clerks</option>';
																			echo '<option value="Service Worker">Service Worker</option>';
																			echo '<option value="Agricultural">Agricultural</option>';
																			echo '<option value="Industrial">Industrial</option>';
																			echo '<option value="Assembler">Assembler</option>';
																			echo '<option value="Labor">Labor</option>';
																			echo '<option value="Unskilled">Unskilled</option>';
																			echo '<option value="Special Occupation">Special Occupation</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SSS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_sss" value="'.$table_row['sss'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">GSIS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_gsis" value="'.$table_row['gsis'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PHIL HEALTH MEMBER</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_phil_health_member" value="'.$table_row['phil_health_member'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PHIL HEALTH DEPENDENT</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_phil_health_dependent" value="'.$table_row['phil_health_dependent'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">FATHER NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_dad_name" value="'.$table_row['dad_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MOTHER NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_mom_name" value="'.$table_row['mom_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">GUARDIAN NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_guardian_name" value="'.$table_row['guardian_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ACCOM NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_accom_name" value="'.$table_row['accom_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">RU_NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_ru_name" value="'.$table_row['ru_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ORGANIZATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_org" value="'.$table_row['org'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ORGANIZATIONAL ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_org_address" value="'.$table_row['org_address'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ORGANIZATION CONTACT</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_org_contact" value="'.$table_row['org'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ORGANIZATIONAL TELEPHONE NO.</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="pwd_org_telno" value="'.$table_row['org_telno'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="pwd_status">';
																			echo '<option selected="selected" value="'.$table_row['status'].'">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													
													elseif($table_name == "client_sen")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;width:10%"><input type="hidden" name="table" value="'.$table_name.'" required /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';														
																echo '<tr>';
																	echo '<td style="border:0;">OSCA_ID</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="sen_osca_id" value="'.$table_row['osca_id'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">new_rep</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_new_rep">';
																			echo '<option selected="selected" value="'.$table_row['new_rep'].'">'.$table_row['new_rep'].'</option>';
																			echo '<option value="New">New</option>';
																			echo '<option value="Replacement">Replacement</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">Barangay</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_brgy">';
																			echo '<option selected="selected" value="'.$table_row['brgy'].'">'.$table_row['brgy'].'</option>';
																			echo '<option value="Bagong Nayon">Bagong Nayon</option>';
																			echo '<option value="Beverly Hills">Beverly Hills</option>';
																			echo '<option value="Calawis">Calawis</option>';
																			echo '<option value="Cupang">Cupang</option>';
																			echo '<option value="Dalig">Dalig</option>';
																			echo '<option value="Dela Paz">Dela Paz</option>';
																			echo '<option value="Inarawan">Inarawan</option>';
																			echo '<option value="Mambugan">Mambugan</option>';
																			echo '<option value="Mayamot">Mayamot</option>';
																			echo '<option value="Munting">Munting</option>';
																			echo '<option value="Dilao">Dilao</option>';
																			echo '<option value="San Isidro">San Isidro</option>';
																			echo '<option value="San Jose">San Jose</option>';
																			echo '<option value="San Juan">San Juan</option>';
																			echo '<option value="San Luis">San Luis</option>';
																			echo '<option value="San Roque">San Roque</option>';
																			echo '<option value="Sta Cruz">Sta Cruz</option>';																			
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">FIRST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="sen_fname" value="'.$table_row['fname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MIDDLE NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_mname" value="'.$table_row['mname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">LAST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="sen_lname" value="'.$table_row['lname'].'" required /></td>';
																echo '</tr>';																
																echo '<tr>';
																	echo '<td style="border:0;">BIRTHDAY</td>';
																	echo '<td style="border:0;"><input type="date" style="width:50%" name="sen_bdate" value="'.$table_row['bdate'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">AGE</td>';
																	echo '<td style="border:0;"><input type="" style="width:7%"  name="sen_age" value="'.$table_row['age'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">GENDER</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_gender">';
																			echo '<option selected="selected" value="'.$table_row['gender'].'">'.$table_row['gender'].'</option>';
																			echo '<option value="Male">Male</option>';
																			echo '<option value="Female">Female</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">CIVIL STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_civilstat">';
																			echo '<option selected="selected" value="'.$table_row['civilstat'].'">'.$table_row['civilstat'].'</option>';
																			echo '<option value="Civil Union">Civil Union</option>';
																			echo '<option value="Divorced">Divorced</option>';
																			echo '<option value="Married">Married</option>';
																			echo '<option value="Separated">Separated</option>';
																			echo '<option value="Single">Single</option>';
																			echo '<option value="Widow">Widow</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BIRTHPLACE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_bplace" value="'.$table_row['bplace'].'" required /></td>';
																echo '</tr>';																
																echo '<tr>';
																	echo '<td style="border:0;">ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_address" value="'.$table_row['address'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">JOB</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_job" value="'.$table_row['job'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">OTHER SKILLS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_other_skills" value="'.$table_row['other_skills'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">TELEPHONE NO.</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_telno" value="'.$table_row['telno'].'" required /></td>';
																echo '</tr>';		
																echo '<tr>';
																	echo '<td style="border:0;">ASSISTANCE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_assistance">';
																			echo '<option selected="selected" value="'.$table_row['assistance'].'">'.$table_row['assistance'].'</option>';
																			echo '<option value="Counseling">Select Assistance</option>';
																			echo '<option value="Financial">Financial</option>';
																			echo '<option value="Medical">Medical</option>';
																			echo '<option value="Burial">Burial</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">REQUIREMENTS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_requirements">';
																			echo '<option selected="selected" value="'.$table_row['requirements'].'">'.$table_row['requirements'].'</option>';
																			echo '<option value="Complete">Complete</option>';
																			echo '<option value="Incomplete">Incomplete</option>';
																			echo '<option value="None">None</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">POST</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_post">';
																			echo '<option selected="selected" value="'.$table_row['post'].'">'.$table_row['post'].'</option>';
																			echo '<option value="Approved">Approved</option>';
																			echo '<option value="Pending">Pending</option>';
																			echo '<option value="Re_Apply">Re-Apply</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BUDGET</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_budget" value="'.$table_row['budget'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="sen_status">';
																			echo '<option selected="selected" value="'.$table_row['status'].'">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													
													}
													elseif($table_name == "client_yth")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;width:10%"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';														
																echo '<tr>';
																	echo '<td style="border:0;">FIRST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_fname" value="'.$table_row['fname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MIDDLE NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_mname" value="'.$table_row['mname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">LAST NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_lname" value="'.$table_row['lname'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">GENDER</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="yth_gender">';
																			echo '<option selected="selected" value="'.$table_row['gender'].'">'.$table_row['gender'].'</option>';
																			echo '<option value="Male">Male</option>';
																			echo '<option value="Female">Female</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">AGE</td>';
																	echo '<td style="border:0;"><input type="" style="width:7%"  name="yth_age" value="'.$table_row['age'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ADDRESS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_address" value="'.$table_row['address'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">RELIGION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_religion" value="'.$table_row['religion'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">BIRTHDAY</td>';
																	echo '<td style="border:0;"><input type="date" style="width:50%"  name="yth_bdate" value="'.$table_row['bdate'].'" required /></td>';
																echo '</tr>';																
																echo '<tr>';
																	echo '<td style="border:0;">BIRTHPLACE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_bplace" value="'.$table_row['bplace'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">FATHER NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_dad_name" value="'.$table_row['dad_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">MOTHER NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_mom_name" value="'.$table_row['mom_name'].'" required /></td>';
																echo '</tr>';																		
																echo '<tr>';
																	echo '<td style="border:0;">ASSISTANCE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="yth_assistance">';
																			echo '<option selected="selected" value="'.$table_row['assistance'].'">'.$table_row['assistance'].'</option>';
																			echo '<option value="Counseling">Select Assistance</option>';
																			echo '<option value="Financial">Financial</option>';
																			echo '<option value="Medical">Medical</option>';
																			echo '<option value="Burial">Burial</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">REQUIREMENTS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="yth_requirements">';
																			echo '<option selected="selected" value="'.$table_row['requirements'].'">'.$table_row['requirements'].'</option>';
																			echo '<option value="Complete">Complete</option>';
																			echo '<option value="Incomplete">Incomplete</option>';
																			echo '<option value="None">None</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">POST</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="yth_post">';
																			echo '<option selected="selected" value="'.$table_row['post'].'">'.$table_row['post'].'</option>';
																			echo '<option value="Approved">Approved</option>';
																			echo '<option value="Pending">Pending</option>';
																			echo '<option value="Re_Apply">Re-Apply</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';																
																echo '<tr>';
																	echo '<td style="border:0;">BUDGET</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="sen_budget" value="'.$table_row['budget'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SIBBLING NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_sib_name" value="'.$table_row['sib_name'].'" required /></td>';
																echo '</tr>';															
																echo '<tr>';
																	echo '<td style="border:0;">SIBBLING GENDER</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="yth_sib_gender">';
																			echo '<option selected="selected" value="'.$table_row['sib_gender'].'">'.$table_row['sib_gender'].'</option>';
																			echo '<option value="Male">Male</option>';
																			echo '<option value="Female">Female</option>';
																		echo '</select>';
																	echo '</td>';																										
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SIBBLING AGE</td>';
																	echo '<td style="border:0;"><input type="" style="width:7%"  name="yth_sib_age" value="'.$table_row['sib_age'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SIBBLING GRADE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_sib_grade" value="'.$table_row['sib_grade'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SIB_ISY</td>';
																	echo '<td style="border:0;"><input type="date" style="width:50%"  name="yth_sib_isy" value="'.$table_row['sib_ISY'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SIB_OSY</td>';
																	echo '<td style="border:0;"><input type="date" style="width:50%"  name="yth_sib_osy" value="'.$table_row['sib_OSY'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SCHOOL</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_school" value="'.$table_row['school'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">SCHOOL LEVEL</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_school_level" value="'.$table_row['school_level'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">YEARS IN SCHOOL</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_school_year" value="'.$table_row['school_year'].'" required /></td>';
																echo '</tr>';																
																echo '<tr>';
																	echo '<td style="border:0;">SKILLS</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_skills" value="'.$table_row['skills'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">INTEREST</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_interest" value="'.$table_row['interest'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">JOB</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_job" value="'.$table_row['job'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">YEARS OF JOB</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_job_year" value="'.$table_row['job_year'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">JOB TITLE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_job_title" value="'.$table_row['job_title'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">JOB INCOME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_job_income" value="'.$table_row['job_income'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">REASON OF LEAVING</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="yth_reason_of_leaving" value="'.$table_row['reason_of_leaving'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ORGANIZATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_org_name" value="'.$table_row['org_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ORGANIZATIONAL POSITION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_org_position" value="'.$table_row['org_position'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">YEARS IN ORGANIZATION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_org_years" value="'.$table_row['org_years'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">YOUTH ORGANIZATION NAME</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_youth_org_name" value="'.$table_row['youth_org_name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">YOUTH ORGANIZATIONAL POSITION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_youth_org_position" value="'.$table_row['youth_org_position'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">YOUTH SERVICE PROVIDER</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="yth_youth_service_provider" value="'.$table_row['youth_service_provider'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="yth_status">';
																			echo '<option selected="selected" value="'.$table_row['status'].'">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "directory")
													{
														$email = $table_row['email'];
														$email_explode = explode('<br>', $email);
														$email1 = $email_explode[0];
														$email2 = $email_explode[1];
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">OFFICE</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="office">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['office'].'</option>';
																			echo '<option value="City Accounting">City Accounting</option>';
																			echo '<option value="City Administrator">City Administrator</option>';
																			echo '<option value="City Budget">City Budget</option>';
																			echo '<option value="City Social Welfare and Development">City Social Welfare and Development</option>';
																			echo '<option value="City Treasury">City Treasury</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">FLOOR</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="floors">';
																			echo '<option value="" disabled="disabled" selected="selected">'.$table_row['floors'].'</option>';
																			echo '<option value="City Hall - 1st Floor">City Hall - 1st Floor</option>';
																			echo '<option value="City Hall - 2nd Floor">City Hall - 2nd Floor</option>';
																			echo '<option value="City Hall - 3rd Floor">City Hall - 3rd Floor</option>';
																			echo '<option value="City Hall - 4th Floor">City Hall - 4th Floor</option>';
																			echo '<option value="GAD Center - 1st Floor">GAD Center - 1st Floor</option>';
																			echo '<option value="GAD Center - 2nd Floor">GAD Center - 2nd Floor</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">TEL NO.</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="telno" value="'.$table_row['telno'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">EMAIL</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="email" value="'.$email1.'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">OTHER EMAIL</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="email" value="'.$email2.'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">OIC</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="oic" value="'.$table_row['oic'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS:</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="status">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "faq")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">QUESTION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="question" value="'.$table_row['question'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">ANSWER</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="answer" value="'.$table_row['answer'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS:</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="status">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "feedback")
													{
														echo '<script language="javascript">';
															echo 'alert("Cannot alter record!");';
															echo 'location.replace("home.php");';
                                                        echo '</script>';
													}
													elseif($table_name == "flow")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';																
																echo '<tr>';
																	echo '<td style="border:0;">DEPARTMENT:</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="department">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['dept'].'</option>';
																			echo '<option value="accounting">Accounting</option>';
																			echo '<option value="admin">Administrator</option>';
																			echo '<option value="budget">Budget</option>';
																			echo '<option value="cswd">CSWD</option>';
																			echo '<option value="treasury">Treasury</option>';
																		echo '</select>';
																	echo '</td>';
																echo '<tr>';
																	echo '<td style="border:0;">INPUT:</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="pwd" value="'.$table_row['input'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PROCESS:</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="pwd" value="'.$table_row['process'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">OUTPUT:</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%"  name="pwd" value="'.$table_row['output'].'" required /></td>';
																echo '</tr>';																										
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "legal")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">TERMS OF USE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="tc" value="'.$table_row['tc'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS:</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="status">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "log")
													{
														echo '<script language="javascript">';
															echo 'alert("Cannot alter record!");';
															echo 'location.replace("home.php");';
                                                        echo '</script>';
													}
													elseif($table_name == "managers")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">NAME:</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="name" value="'.$table_row['name'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PASSWORD:</td>';
																	echo '<td style="border:0;"><input type="password" style="width:50%"  name="pwd" value="'.$table_row['pwd'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">PHOTO:</td>';
																	echo '<td style="border:0;"><input type="file" name="pic" value="" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS:</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="status">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
													elseif($table_name == "services")
													{
														echo '<table class="art-article" cellpadding="2" cellspacing="2" style="border:0;width:100%;" class="static_text02">';
															echo '<tbody>';
																echo '<tr>';
																	echo '<td style="border:0;"><input type="hidden" name="table" value="'.$table_name.'" /></td>';
																	echo '<td style="border:0;"><input type="hidden" name="id" value="'.$row_id.'" /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">TITLE</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="title" value="'.$table_row['title'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">DIVISION</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="division">';
																			echo '<option value="" disabled="disabled" selected="selected">'.$table_row['division'].'</option>';
																			echo '<option value="Relief and Public Assistance Division">Relief and Public Assistance Division</option>';
																			echo '<option value="Community Outreach Division">Community Outreach Division</option>';
																			echo '<option value="Residential and Rehabilitation Division">Residential and Rehabilitation Division</option>';
																			echo '<option value="Special Programs and Projects">Special Programs and Projects</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">DESCRIPTION</td>';
																	echo '<td style="border:0;"><input type="" style="width:50%" name="description" value="'.$table_row['description'].'" required /></td>';
																echo '</tr>';
																echo '<tr>';
																	echo '<td style="border:0;">STATUS:</td>';
																	echo '<td style="border:0;">';
																		echo '<select name="status">';
																			echo '<option disabled="disabled" selected="selected">'.$table_row['status'].'</option>';
																			echo '<option value="Active">Active</option>';
																			echo '<option value="Inactive">Inactive</option>';
																		echo '</select>';
																	echo '</td>';
																echo '</tr>';
															echo '</tbody>';
														echo '</table>';
													}
												}
												echo '<br />';
												echo '<input type="submit" name="update" value="Update Record" class="art-button" />';
											}
										?>
									</form>
									</div>
								</article>
							</div>
						</div>
					</div>
				</div>
				<hr /><?php include("footer.php"); ?>
			</div><br />
		</div>
	</body>
</html>